"""cascade delete

Revision ID: 1ce0b65fd713
Revises: 3f53be8325af
Create Date: 2022-05-29 22:47:22.856248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce0b65fd713'
down_revision = '3f53be8325af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('element_bookmarks_group_id_fkey', 'element', type_='foreignkey')
    op.create_foreign_key(None, 'element', 'bookmarks_group', ['bookmarks_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_group_bookmarks_group_id_fkey', 'user_group', type_='foreignkey')
    op.drop_constraint('user_group_user_id_fkey', 'user_group', type_='foreignkey')
    op.create_foreign_key(None, 'user_group', 'web_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_group', 'bookmarks_group', ['bookmarks_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.create_foreign_key('user_group_user_id_fkey', 'user_group', 'web_user', ['user_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('user_group_bookmarks_group_id_fkey', 'user_group', 'bookmarks_group', ['bookmarks_group_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint(None, 'element', type_='foreignkey')
    op.create_foreign_key('element_bookmarks_group_id_fkey', 'element', 'bookmarks_group', ['bookmarks_group_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
