"""add field for group

Revision ID: 3f53be8325af
Revises: cc49f27f27ab
Create Date: 2022-05-23 01:26:50.367321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f53be8325af'
down_revision = 'cc49f27f27ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks_group', sa.Column('unique_url', sa.String(), nullable=True))
    op.drop_column('bookmarks_group', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks_group', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('bookmarks_group', 'unique_url')
    # ### end Alembic commands ###
