"""Initial migration

Revision ID: cc49f27f27ab
Revises: 
Create Date: 2022-05-15 21:58:32.064284

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc49f27f27ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('bookmarks_group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('is_public', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('element',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('img_src', sa.String(), nullable=True),
                    sa.Column('tags', sa.String(), nullable=True),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('bookmarks_group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmarks_group_id'], ['bookmarks_group.id'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('web_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('bookmarks_group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['bookmarks_group_id'], ['bookmarks_group.id'], onupdate='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['web_user.id'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_unique_constraint(None, 'web_user', ['email'])
    # ### end Alembic commands ###
    op.execute(
        f"INSERT INTO web_user (email, password) "
        f"VALUES ("
        f"'admin@test.com', "
        f"'pbkdf2:sha256:260000$SM52DaZFYxMgDG2P$a103b53857db035d5af68b128b482b3d6aa623ba6c4bb44e697ea83d2fb3090b'"
        f")"
    )
    op.execute(
        f"INSERT INTO bookmarks_group (title) VALUES ('test_group')"
    )
    op.execute(
        f"INSERT INTO user_group (user_id, bookmarks_group_id) VALUES ('1', '1')"
    )
    op.execute(
        f"INSERT INTO element (title, tags, source, bookmarks_group_id) "
        f"VALUES ('test_element1', 'eee boy', 'source', '1')"
    )
    op.execute(
        f"INSERT INTO element (title, tags, source, bookmarks_group_id) "
        f"VALUES ('test_element2', 'eee boy', 'source', '1')"
    )
    op.execute(
        f"INSERT INTO element (title, tags, source, bookmarks_group_id) "
        f"VALUES ('test_element3', 'eee boy', 'source', '1')"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group')
    op.drop_table('element_group')
    op.drop_table('web_user')
    op.drop_table('group')
    op.drop_table('element')
    # ### end Alembic commands ###
